#!/bin/bash -x
#add a forward from a to b
# use   ./addForward  a b

if [ $(echo $0 | grep '^/') ]; then
    path=$(dirname $0)
else
    path=$(pwd)
fi
echo $path



echo "$1 to $2"
fromUrl="$1"
toPath="$2"
echo "start...."
cp -r $path/mould/mould-path /etc/nginx/sites-available/$fromUrl
echo "add formUrl :${fromUrl}"
sed -i "s/FROM_URL/${fromUrl}/g"   /etc/nginx/sites-available/$fromUrl
echo "add toPath :${toPath//\//\\/}"
sed -i "s/TO_PATH/${toPath//\//\\/}/g"     /etc/nginx/sites-available/$fromUrl
echo "mkdir ${toPath}"
mkdir -pv ${toPath}
ln -s /etc/nginx/sites-available/$fromUrl /etc/nginx/sites-enabled/$fromUrl
service nginx reload
